import { createServer, type IncomingMessage, type ServerResponse } from "node:http"
import { readFileSync } from "node:fs"
import * as Schema from "effect/Schema"
import { createR2DownloadGrantIssuer, type DownloadGrantIssuer } from "./r2-download-grant.ts"

const Request = Schema.Struct({ objectKey: Schema.NonEmptyString, expiresAt: Schema.NonEmptyString })
export function downloadGrantServiceConfig(env: Record<string, string | undefined>) { const accountId = env.R2_ACCOUNT_ID; const bucket = env.R2_BUCKET; const endpoint = env.R2_ENDPOINT; const credentialsPath = env.R2_DOWNLOAD_CREDENTIALS_PATH; const secretPath = env.ASTRO_DOWNLOAD_GRANT_SHARED_SECRET_PATH; if (!accountId || !bucket || !endpoint || !credentialsPath || !secretPath || !/^[a-f0-9]{32}$/.test(accountId) || !/^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/.test(bucket) || !/^\/run\/secrets\/[A-Za-z0-9._-]+$/.test(credentialsPath) || !/^\/run\/secrets\/[A-Za-z0-9._-]+$/.test(secretPath)) throw new Error("Download grant signer requires bounded R2 read credentials and a shared secret"); if (endpoint !== `https://${accountId}.r2.cloudflarestorage.com`) throw new Error("Download grant signer requires the account R2 endpoint"); return { bucket, endpoint, credentialsPath, secretPath } }
export function createDownloadGrantService(config: ReturnType<typeof downloadGrantServiceConfig>, dependencies: { readonly secret?: string; readonly issuer?: DownloadGrantIssuer } = {}) { const secret = dependencies.secret ?? readFileSync(config.secretPath, "utf8").trim(); if (secret.length < 32 || /[\r\n]/.test(secret)) throw new Error("Download grant shared secret is invalid"); const issuer = dependencies.issuer ?? createR2DownloadGrantIssuer(config); return createServer(async (request: IncomingMessage, response: ServerResponse) => { if (request.method !== "POST" || request.url !== "/internal/download-grants" || request.headers.authorization !== `Bearer ${secret}`) return response.writeHead(401).end(); let text = ""; for await (const chunk of request) { text += chunk; if (Buffer.byteLength(text) > 16_384) return response.writeHead(413).end() } try { const input = Schema.decodeUnknownSync(Request)(JSON.parse(text)); const url = await issuer.issue(input); response.writeHead(200, { "content-type": "application/json", "cache-control": "no-store" }).end(JSON.stringify({ url })) } catch { response.writeHead(400).end() } }) }
if (process.argv[1]?.endsWith("download-grant-service.ts")) { const server = createDownloadGrantService(downloadGrantServiceConfig(process.env)); server.listen(Number(process.env.ASTRO_DOWNLOAD_GRANT_PORT ?? "8791"), "0.0.0.0") }
